version: 2

jobs:
  build:
    working_directory: ~/tyche

    docker:
      - image: circleci/node:12.10.0

    steps:
      - checkout

      - attach_workspace:
          at: ~/tyche

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # lint
      - run: yarn lint

      # test
      - run: yarn test

      # build
      - run: yarn build

      # keep app.yaml & dist
      - persist_to_workspace:
          root: .
          paths:
            - app.yaml
            - dist/*

  deploy:
    working_directory: ~/tyche
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout

      - attach_workspace:
          at: ~/tyche

      - run:
          name: Asset Check
          command: |
            echo $PWD
            ls -aslh .

      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud --quiet app deploy app.yaml --verbosity=info

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
